# Generated by Django 5.1.7 on 2025-03-28 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='Должность')),
                ('is_supervisor', models.BooleanField(default=False, verbose_name='Супервизор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('deadline', models.DateTimeField(verbose_name='Срок исполнения')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'В работе'), ('under_review', 'На проверке'), ('resubmit', 'Требует доработки'), ('completed', 'Завершена'), ('delayed', 'Отложена'), ('cancelled', 'Отменена')], default='created', max_length=13, verbose_name='Статус')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='task_files/%Y/%m/%d/')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.employee', verbose_name='Исполнитель')),
                ('parental_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.task', verbose_name='Родительская задача')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
